name: ğŸ³ Lint Dockerfile

on:
  pull_request:
    paths:
      - 'docker/Dockerfile'
  push:
    paths:
      - 'docker/**'
  workflow_dispatch:

jobs:
  validate-dockerfile:
    runs-on: ubuntu-22.04

    steps:
      - name: ğŸš€ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ”§ Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "docker/Dockerfile"
